//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOG.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public decimal id_post { get; set; }
        public string titulo_post { get; set; }
        public string texto_post { get; set; }
    }
}
