//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPresentacion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISvcPost")]
    public interface ISvcPost {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Crear", ReplyAction="http://tempuri.org/ISvcPost/CrearResponse")]
        bool Crear(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Crear", ReplyAction="http://tempuri.org/ISvcPost/CrearResponse")]
        System.Threading.Tasks.Task<bool> CrearAsync(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Modificar", ReplyAction="http://tempuri.org/ISvcPost/ModificarResponse")]
        bool Modificar(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Modificar", ReplyAction="http://tempuri.org/ISvcPost/ModificarResponse")]
        System.Threading.Tasks.Task<bool> ModificarAsync(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Eliminar", ReplyAction="http://tempuri.org/ISvcPost/EliminarResponse")]
        bool Eliminar(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/Eliminar", ReplyAction="http://tempuri.org/ISvcPost/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string xmlPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/ListarTodo", ReplyAction="http://tempuri.org/ISvcPost/ListarTodoResponse")]
        string ListarTodo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPost/ListarTodo", ReplyAction="http://tempuri.org/ISvcPost/ListarTodoResponse")]
        System.Threading.Tasks.Task<string> ListarTodoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcPostChannel : WpfPresentacion.ServiceReference1.ISvcPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcPostClient : System.ServiceModel.ClientBase<WpfPresentacion.ServiceReference1.ISvcPost>, WpfPresentacion.ServiceReference1.ISvcPost {
        
        public SvcPostClient() {
        }
        
        public SvcPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Crear(string xmlPost) {
            return base.Channel.Crear(xmlPost);
        }
        
        public System.Threading.Tasks.Task<bool> CrearAsync(string xmlPost) {
            return base.Channel.CrearAsync(xmlPost);
        }
        
        public bool Modificar(string xmlPost) {
            return base.Channel.Modificar(xmlPost);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAsync(string xmlPost) {
            return base.Channel.ModificarAsync(xmlPost);
        }
        
        public bool Eliminar(string xmlPost) {
            return base.Channel.Eliminar(xmlPost);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string xmlPost) {
            return base.Channel.EliminarAsync(xmlPost);
        }
        
        public string ListarTodo() {
            return base.Channel.ListarTodo();
        }
        
        public System.Threading.Tasks.Task<string> ListarTodoAsync() {
            return base.Channel.ListarTodoAsync();
        }
    }
}
